.TH Anakin\&Dey 7
.SH Name
See Title
.SH Synopsis
Math Major @ UIUC with a large interest in Abstract Algebra and Algorithms
.SH Description
My main interest in mathematics is Abstract Algebra and my main interest in computer science is Algorithms. Both of these stem from a general interest in exploring properties of objects with a set of constraints and explore all the possibilites that arise from the inclusion and exclusion of these constraints.
.SH Options
.B --email 
.OP anakind2@illinois.edu

.B --phone 
.OP 331-250-1378

.B --repo 
.OP github.com/spamakin

.B --network 
.OP linkedin.com/anakin-dey

." idea stolen from https://nicholas.sh/
