.TH "Anakin Dey " 7 "" "" "User Guide"
.PP
.SH Name
^^^ See Title
.SH Synopsis
man <(curl https://www.anakin-dey.com/anakin.7)
.PP
.SH Options
.B --email 
.OP anakind2@illinois.edu
.PP
.B --repo 
.OP github.com/spamakin
.PP
.B --network 
.OP linkedin.com/anakin-dey
.PP
.B --resume
.OP www.anakin-dey.com/Anakin_Dey_Resume.pdf
.SH Description
    Math Major @ UIUC with a large interest in Abstract Algebra and Algorithms

   
.SH Current
.IP\bu20
  Course Assistant for \fICS173\fP 
  Course Assistant for \fICS374\fP 
  Doing Research under Melkior Ornik.

.SH Former
.IP\bu 
  Software engineering intern for \fISiteIQ\fP.

." idea stolen from https://nicholas.sh/
