.TH "Anakin Dey " 7 "" "" "User Guide"
.PP
.SH Name
^^^ See Title
.SH Synopsis
man <(curl https://www.anakin-dey.com/anakin.7)
.PP
.SH Options
.B --email 
.OP anakind2@illinois.edu
.PP
.B --repo 
.OP github.com/spamakin
.PP
.B --network 
.OP linkedin.com/anakin-dey
.PP
.B --resume
.OP www.anakin-dey.com/Anakin_Dey_Resume.pdf
.SH Description
    Math Major @ UIUC with a large interest in Abstract Algebra and Algorithms

   
.SH Current
.IP\bu20
  Software Engineering at \fICME Group\fP
  Course Assistant for \fICS173\fP 
  Course Assistant for \fICS374\fP 
  Doing research under Melkior Ornik.

.SH Research
.IP\bu20
  Post-Disaster Repair Crew Assignment Optimization Using Minimum Latency
    \fBAbout:\fP Preliminary work on heuristic algorithms for the m-MWLP
    \fBPDF:\fP https://arxiv.org/abs/2206.00597
    \fBSource:\fP https://github.com/leadcatlab/MWLP-Storm-Repair

.SH Former
.IP\bu 
  Software engineering intern for \fISiteIQ\fP.
  Course Assistant for \fICS125\fP

." idea stolen from https://nicholas.sh/
